
enum CertificatesCategory{
    AR_VR = "AR VR",
    DATA_SCIENCE = "Data Science",
    DEV_OPS = "DevOps",
    FULLSTACK = "FullStack",
    GIS = "GIS",
    IOS = "iOS",
    PROJECT_MANAGEMENT = "Project Management",
    WORDPRESS = "Wordpress"
}

interface CertificatesTypes{
    name:string
    category:CertificatesCategory
    skills:string[]
    verified:boolean
    verifiedBy:string[]
    verifyCode:string
    date:string
    month:string
    year:string
    url?:string
    image:string
    top: boolean
}

const Certificates:CertificatesTypes[] = [
    //VR AR
    {
        name: "AR Development Techniques 01: Basic Concepts",
        category: CertificatesCategory.AR_VR,
        skills: ["Unity", "Augmented Reality"],
        verified: true,
        verifiedBy: ["Linkedin"],
        verifyCode: "f3f8b72213533c4d9b98c4645205d0526fa162edfec91d3889eadef84c76c075",
        date: "16",
        month: "October",
        year: "2023",
        image: "/images/certificates/cert_foundation_mozilla.jpg",
        top: false
    },
    {
        name:"AR Development Techniques 02: Lighting and Physics",
        category:CertificatesCategory.AR_VR,
        skills:["Unity", "Augmented Reality"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"4b2f68459e2596f040b4ea9121745bb0b23c86474cb85d11e4de707cfc271165",
        date:"02",
        month:"November",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false
    },
    {
        name:"Virtual Reality Foundations",
        category:CertificatesCategory.AR_VR,
        skills:["Unity", "Augmented Reality"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"bc55507e1e784903ea612995204157442c8496f80911d992f51919448069f66b",
        date:"18",
        month:"July",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false
    },
    //Data Science
    {
        name:"Data Science Foundations: Python Scientific Stack",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"f0acc5c61889f9574d590dbab366da6437ddbebdf70c1b8c6cc78c906872def6",
        date:"21",
        month:"July",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false
    },
    {
        name:"Deep Learning: Getting Started",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Machine Learning", "Deep Learning"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"3e596553be417a852ad40dcc0ecf38087e54dadf7a9f188c556c40a7d7be21c6",
        date:"24",
        month:"July",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false
    },
    {
        name:"OpenCV for Python Developers",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Computer Vision", "OpenCV"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"96569e1cc1214a9e8325aae7e5c86f74eafd3ca3fc6e84b8267d91370e5d7c8f",
        date:"12",
        month:"August",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false
    },
    {
        name:"Python for Data Science Essential Training Part 1",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"96569e1cc1214a9e8325aae7e5c86f74eafd3ca3fc6e84b8267d91370e5d7c8f",
        date:"10",
        month:"July",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false
    },
    {
        name:"Python for Data Science Essential Training Part 2",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"96569e1cc1214a9e8325aae7e5c86f74eafd3ca3fc6e84b8267d91370e5d7c8f",
        date:"19",
        month:"July",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false
    },
    {
        name:"Data Science Methodology",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"6G4NMZ275RZK",
        date:"30",
        month:"January",
        year:"2021",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/7JP2NYZ9ALZN"
    }, 
    {
        name:"Databases and SQL for Data Science with Python",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"6G4NMZ275RZK",
        date:"8",
        month:"February",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/6G4NMZ275RZK"
    },
    {
        name:"Introduction to Data Science in Python",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "University for Michigan"],
        verifyCode:"TRWNHR5JQWKL",
        date:"13",
        month:"May",
        year:"2020",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/TRWNHR5JQWKL"
    },
    {
        name:"Python for Data Science, AI & Development",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "University for Michigan"],
        verifyCode:"BU5BXXLV8HCP",
        date:"11",
        month:"July",
        year:"2021",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/BU5BXXLV8HCP"
    },
    {
        name:"Python Project for Data Science",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "University for Michigan"],
        verifyCode:"ZC7RGBN7M257",
        date:"12",
        month:"July",
        year:"2021",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/ZC7RGBN7M257"
    },
    {
        name:"Tools for Data Science",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "University for Michigan"],
        verifyCode:"XL9PYWB75BGQ",
        date:"12",
        month:"July",
        year:"2021",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/XL9PYWB75BGQ"
    },
    {
        name:"What is Data Science?",
        category:CertificatesCategory.DATA_SCIENCE,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "University for Michigan"],
        verifyCode:"F2XJKP3C2AXA",
        date:"09",
        month:"June",
        year:"2021",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/F2XJKP3C2AXA"
    },
    //DevOps
    {
        name:"Cloud Application Development Foundations",
        category:CertificatesCategory.DEV_OPS,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"6NKYCXC5PGW8",
        date:"06",
        month:"February",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/specialization/6NKYCXC5PGW8"
    },
    {
        name:"Getting Started with Git and GitHub",
        category:CertificatesCategory.DEV_OPS,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"B4MJWEX7UZ4K",
        date:"25",
        month:"January",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/B4MJWEX7UZ4K"
    },
    {
        name:"Introduction to Containers w/ Docker, Kubernetes & OpenShift",
        category:CertificatesCategory.DEV_OPS,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"C7QRCC2ELNLM",
        date:"11",
        month:"February",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/C7QRCC2ELNLM"
    },
    //Fullstack
    {
        name:"Developing for Web Performance",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"4b3fb75a9ae610b31f22111bbef976231fb81cd3c4cac2e1e2cae50409d613a7",
        date:"14",
        month:"December",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"ESLint: Integrating with Your Workflow",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"eb2f6df585cab0868c425198e2bebcbd0b41a01eb7e46297c19bc196f8f1e1e8",
        date:"16",
        month:"April",
        year:"2024",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"Foundational JavaScript Security",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"e37822cd6ddff38d32017c881cf06ff3c997a07e4d6dc5588dee69245f8a232c",
        date:"04",
        month:"May",
        year:"2024",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"Full Stack Web Development with Flask",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"900817fa9988e9e2ac1598b40f38ec4ed2fe4e36eaa2d41b52202d16e8969cd3",
        date:"26",
        month:"July",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"JavaScript: Best Practices for Code Formatting",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"1d4ab03612ffc16316f23bde281db56e753575e0cb4b3c7f47fc27bdccc5a110",
        date:"09",
        month:"November",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"JavaScript: Best Practices for Data",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"97822ea75347472d3ec2549070c425fca04c0a2c53e693d3cee74382441c0871",
        date:"12",
        month:"April",
        year:"2024",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"JavaScript Essential Training",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"ade5db626733632a7967c8bf148d965e16b6f00fac0b94b964d2c6a15a431eb6",
        date:"16",
        month:"May",
        year:"2024",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"JavaScript Foundations Professional Certificate by Mozilla",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin", "Mozilla"],
        verifyCode:"43461ea6f04da4997d5c5415b878216916abc06ce361c40b4ee4ec281c83d9d8",
        date:"16",
        month:"May",
        year:"2024",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"JavaScript: Test-Driven Development (ES6)",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"2430d229c0bc7d2821d7acd79965e4b5aa3fbfb96f5c55df4ad511133de1b8f6",
        date:"16",
        month:"April",
        year:"2024",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"Learning the JavaScript Language",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"e6746f2a66943a3e2d715f0e4a4978ef3efac00fcaa7b5e4346a20c8c7a91cbe",
        date:"14",
        month:"May",
        year:"2024",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"React: Accessibility",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"90de43ab5f6dc07a5163ec8a6c26e8eab0978a645f26f78e48d9d2cc5cb330ac",
        date:"14",
        month:"August",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"React Hooks",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"f05c8b6f674aff75c4f84bfa485e5f13743bd2afc5ace9879919c0995881c32e",
        date:"15",
        month:"August",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"React.js: Building an Interface",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"6d6c43242c04b359019cc160a16e5cc6aacf1367bc8726c350628f32d21ce8bf",
        date:"10",
        month:"October",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"React.js Essential Training",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"ef79fc4a4599a8f51ac061d52ee82b1d0cf04d1362d1abaa4e01592b817cd1c0",
        date:"14",
        month:"August",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"Top Five Things to Know in Advanced SQL",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"6d544f5d3a53670359b2d166f94a5d28e7bff6e5d44843d09ffffb504104f343",
        date:"12",
        month:"March",
        year:"2024",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"TypeScript Essential Training",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Linkedin"],
        verifyCode:"c218f8b1dba1df8470ac8064669d1cbb88fcbdfb729b86d6756bfe4b0aebcf82",
        date:"09",
        month:"January",
        year:"2024",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
    },
    {
        name:"Application Development using Microservices and Serverless",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"P57XB58HNUVE",
        date:"22",
        month:"February",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/P57XB58HNUVE"
    },
    {
        name:"Developing AI Applications with Python and Flask",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"FNSFLLHHV5FB",
        date:"09",
        month:"February",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/FNSFLLHHV5FB"
    },
    {
        name:"Developing Back-End Apps with Node.js and Express",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"BK747PSGUC32",
        date:"08",
        month:"February",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/BK747PSGUC32"
    },
    {
        name:"Developing Front-End Apps with React",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"BPZJ33U8AGPR",
        date:"08",
        month:"February",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/BPZJ33U8AGPR"
    },
    {
        name:"Django Application Development with SQL and Databases",
        category:CertificatesCategory.FULLSTACK,
        skills:["Python", "Data Science"],
        verified:true,
        verifiedBy:["Coursera", "IBM"],
        verifyCode:"ZY28FSTTRANS",
        date:"21",
        month:"February",
        year:"2023",
        image:"/images/certificates/cert_foundation_mozilla.jpg",
        top: false,
        url: "https://coursera.org/verify/ZY28FSTTRANS"
    },

]

